---
  - name: update
    shell: "{{item}}"
    with_items:
      - wget --quiet -O- "https://repository.rudder.io/apt/rudder_apt_key.pub" | apt-key add -
      - echo "deb http://repository.rudder.io/apt/5.0/ $(lsb_release -cs) main" > /etc/apt/sources.list.d/rudder.list
      - apt update

  - name: install apache2
    apt: name={{item}} update_cache=yes state=latest
    with_items:
      - rudder-agent

  - name: update
    shell: "{{item}}"
    with_items:
      - echo '{{ipRudder}}' > /var/rudder/cfengine-community/policy_server.dat
      - service rudder-agent start
